# Site settings
title: "Erin's Pet Sitting Services"
description: "Trusted pet care, dog walking, and sitting services in Northfleet & Gravesend."
url: "https://erinspetsittingservices.co.uk"
baseurl: ""

# Author info
author:
  name: "Erin's Pet Sitting Services"
  email: "erinspetsittingservices@mail.com"
  tel: "07466159400"
  whatsapp: "https://wa.me/447466159400"
  messenger: "https://m.me/61560319745772"
  facebook: "https://www.facebook.com/people/Erins-Pet-Sitting-Services/61560319745772"
  instagram: "https://www.instagram.com/ErinsPetSittingServicesKent"

links:
  privacy: "/info/privacy-policy"


tallycontactdef: "yP2aKp"

# Build settings
markdown: kramdown
permalink: /:title/